# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages

os:
  - linux
  - osx

r:
  - release
  - devel
  
matrix:
  exclude:
    - r: devel
      os: osx

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - ASAN="-fsanitize=address -fno-omit-frame-pointer"
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
    - HDF5_VERSION=1.8.17
    - HDF5_RELEASE_URL="https://support.hdfgroup.org/ftp/HDF5/releases"

before_install:
  - chmod +x travis_setup.sh
  - ./travis_setup.sh

addons:
  apt:
    packages:
      - subversion
      - autoconf
      - build-essential
      - libtool
      - libmagick++-dev
  homebrew:
    packages:
      - libgit2

#bioc_packages:
#  - GenomeInfoDbData
#  - DESeq2
#  - MAST
#  - S4Vectors
#  - SummarizedExperiment
#  - SingleCellExperiment

r_github_packages:
  - mojaveazure/loomR

warnings_are_errors: false
