name: Integration Checks

# Because `develop` is a protected branch this workflow is triggered when a PR 
# is opened/updated and again when it is merged.
on:
  push:
    branches: 
    - develop
  pull_request:
    branches: 
    - develop

jobs:
  check-package:
    runs-on: ubuntu-latest
    
    # Use the `satijalab/seurat-ci` Docker image as the runner environment. 
    # This image is pre-configured with everything required for running
    # integration checks, for more details, see
    # https://hub.docker.com/repository/docker/satijalab/seurat-ci/general.
    container:
      image: satijalab/seurat-ci:latest

    steps:
      # Pull the latest changes from the repository down to the runner.
      - name: Checkout
        uses: actions/checkout@v4
      
      # Install the package and all its dependencies using scripts from 
      # `littler`, see https://eddelbuettel.github.io/littler/ for details. 
      # `Seurat` is listed under "Enhances" so it also needs to be installed. 
      - name: Install Dependencies
        run: installDeps.r -s && install.r Seurat
      
      # Run CRAN checks, if any ERRORs or WARNINGs are raised the check fails.
      - name: Run Checks
        run: rcmdcheck::rcmdcheck(args = "--as-cran", error_on="warning")
        shell: Rscript {0}
        continue-on-error: true
      
      # Build the `pkgdown` site, if any errors are raised the check fails.
      - name: Build Website
        run: | 
          pkgdown::build_site_github_pages(
            new_process = FALSE, 
            install = FALSE
          )
        shell: Rscript {0}
